/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.WindowConstants;
import java.sql.*;
import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Victor
 */
public class InformacionUsuario extends javax.swing.JFrame {

    String user = "";
    String user_update = "";
    int ID;

    /**
     * Creates new form InformacionUsuario
     */
    public InformacionUsuario() {
        initComponents();
        user = Login.user;
        user_update = GestionarUsuarios.user_update;
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("informacion del usuario " + user_update + " Secion de " + user);
        setSize(630, 450);

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        /// cambiar icono del programa 
        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel1_Walpaper.getWidth(), jLabel1_Walpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel1_Walpaper.setIcon(icono);
        this.repaint();
        // esta linea informa el usuari oque se esta modoficiando 
        jLabel_titulo.setText("Informacion del usuario " + user_update);
        //// aqui se muestra la informacion del usuario 
        try {
            Connection cn = Conexion.Conectar();
            String ConsultaSql = "select * from usuarios where username = '" + user_update + "'";
            PreparedStatement pst = cn.prepareStatement(ConsultaSql);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                ID = rs.getInt("id_usuario");

                TxtNombre.setText(rs.getString("nombre_usuario"));
                Txt_mail.setText(rs.getString("email"));
                TxtTelefono.setText(rs.getString("telefono"));
                TxtUsername.setText(rs.getString("username"));
                TxtRegistradopor.setText(rs.getString("registrado_por"));

                CMB_niveles.setSelectedItem(rs.getString("tipo_nivel"));
                CCMB_Estatus.setSelectedItem(rs.getString("estatus"));

            }
            cn.close();

        } catch (SQLException e) {
            System.err.print("error cargando usuarios " + e);
            JOptionPane.showMessageDialog(null, "contacte al adiminstrador");

        }

    }

    //// metodo que cambia el icono del jform
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_titulo = new javax.swing.JLabel();
        jLabel2_Nombre = new javax.swing.JLabel();
        jLabel2_Nombre1 = new javax.swing.JLabel();
        jLabel2_Nombre2 = new javax.swing.JLabel();
        jLabel2_Nombre3 = new javax.swing.JLabel();
        jLabel2_Nombre4 = new javax.swing.JLabel();
        jLabel2_Nombre5 = new javax.swing.JLabel();
        jLabel2_Nombre6 = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        Txt_mail = new javax.swing.JTextField();
        TxtTelefono = new javax.swing.JTextField();
        TxtUsername = new javax.swing.JTextField();
        TxtRegistradopor = new javax.swing.JTextField();
        CCMB_Estatus = new javax.swing.JComboBox<>();
        CMB_niveles = new javax.swing.JComboBox<>();
        jButton1_Actualizar = new javax.swing.JButton();
        jButton1_RestauraPASS = new javax.swing.JButton();
        jLabel2_footer = new javax.swing.JLabel();
        jLabel1_Walpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_titulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_titulo.setText("Informacion del usuario");
        getContentPane().add(jLabel_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel2_Nombre.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2_Nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2_Nombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2_Nombre.setText("jLabel2");
        getContentPane().add(jLabel2_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel2_Nombre1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2_Nombre1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2_Nombre1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2_Nombre1.setText("I mail");
        getContentPane().add(jLabel2_Nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel2_Nombre2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2_Nombre2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2_Nombre2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2_Nombre2.setText("Telefono :");
        getContentPane().add(jLabel2_Nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel2_Nombre3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2_Nombre3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2_Nombre3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2_Nombre3.setText("Permisos ");
        getContentPane().add(jLabel2_Nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel2_Nombre4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2_Nombre4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2_Nombre4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2_Nombre4.setText("Username");
        getContentPane().add(jLabel2_Nombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        jLabel2_Nombre5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2_Nombre5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2_Nombre5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2_Nombre5.setText("Estatus");
        getContentPane().add(jLabel2_Nombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        jLabel2_Nombre6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2_Nombre6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2_Nombre6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2_Nombre6.setText("Registrado por");
        getContentPane().add(jLabel2_Nombre6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        TxtNombre.setBackground(new java.awt.Color(153, 153, 255));
        TxtNombre.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        TxtNombre.setForeground(new java.awt.Color(255, 255, 255));
        TxtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(TxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 210, 20));

        Txt_mail.setBackground(new java.awt.Color(153, 153, 255));
        Txt_mail.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        Txt_mail.setForeground(new java.awt.Color(255, 255, 255));
        Txt_mail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Txt_mail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Txt_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 210, 20));

        TxtTelefono.setBackground(new java.awt.Color(153, 153, 255));
        TxtTelefono.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        TxtTelefono.setForeground(new java.awt.Color(255, 255, 255));
        TxtTelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtTelefono.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(TxtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 210, 20));

        TxtUsername.setBackground(new java.awt.Color(153, 153, 255));
        TxtUsername.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        TxtUsername.setForeground(new java.awt.Color(255, 255, 255));
        TxtUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtUsername.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TxtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(TxtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 210, 20));

        TxtRegistradopor.setBackground(new java.awt.Color(153, 153, 255));
        TxtRegistradopor.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        TxtRegistradopor.setForeground(new java.awt.Color(255, 255, 255));
        TxtRegistradopor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtRegistradopor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TxtRegistradopor.setEnabled(false);
        getContentPane().add(TxtRegistradopor, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 210, 20));

        CCMB_Estatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        getContentPane().add(CCMB_Estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, -1, -1));

        CMB_niveles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Capturista", "Tecnico" }));
        getContentPane().add(CMB_niveles, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jButton1_Actualizar.setBackground(new java.awt.Color(153, 153, 225));
        jButton1_Actualizar.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jButton1_Actualizar.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_Actualizar.setText("Actualizar Usuario");
        jButton1_Actualizar.setBorder(null);
        jButton1_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_ActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 210, 35));

        jButton1_RestauraPASS.setBackground(new java.awt.Color(153, 153, 225));
        jButton1_RestauraPASS.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jButton1_RestauraPASS.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_RestauraPASS.setText("Restaura password");
        jButton1_RestauraPASS.setBorder(null);
        jButton1_RestauraPASS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_RestauraPASSActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_RestauraPASS, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 210, 35));

        jLabel2_footer.setText("Creado por Victor Carreño ");
        getContentPane().add(jLabel2_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, -1));

        jLabel1_Walpaper.setForeground(new java.awt.Color(153, 153, 255));
        getContentPane().add(jLabel1_Walpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUsernameActionPerformed

    private void jButton1_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_ActualizarActionPerformed
        // TODO add your handling code here:
        int permisos_cmb;
        int estatus_cmb;
        int validacion = 0;

        String Nombre;
        String mail;
        String Telefono;
        String username;

        String permisos_String = "";
        String estatus_String = "";

        mail = Txt_mail.getText().trim();
        Nombre = TxtNombre.getText().trim();
        Telefono = TxtTelefono.getText().trim();
        username = TxtUsername.getText().trim();

        permisos_cmb = CMB_niveles.getSelectedIndex() + 1;
        estatus_cmb = CCMB_Estatus.getSelectedIndex() + 1;

        if (mail.equals("")) {
            Txt_mail.setBackground(Color.red);
            validacion++;

        }
        if (Nombre.equals("")) {
            TxtNombre.setBackground(Color.red);
            validacion++;

        }
        if (Telefono.equals("")) {
            TxtTelefono.setBackground(Color.red);
            validacion++;

        }
        if (username.equals("")) {
            TxtUsername.setBackground(Color.red);
            validacion++;

        }
        if (validacion == 0) {
            //esto trasforma el combobox de int a string 
            if (permisos_cmb == 1) {
                permisos_String = "Administrador";
            } else if (permisos_cmb == 2) {
                permisos_String = "Capturista";
            } else if (permisos_cmb == 3) {
                permisos_String = "Tecnico";
            }

            /// estatus CBM 
            if (estatus_cmb == 1) {
                estatus_String = "Activo";
            } else if (estatus_cmb == 2) {
                estatus_String = "Inactivo";
            }

            try {
                /// aqui se valida si el usuario que se esta actualizando existe en la BD 
                Connection cn = Conexion.Conectar();
                String ConsultaSQLValidaExistenciaDeUsuario = "select username from usuarios where username= '" + username + "' and not id_usuario = '" + ID + "'";
                PreparedStatement psr = cn.prepareStatement(ConsultaSQLValidaExistenciaDeUsuario);
                ResultSet rs = psr.executeQuery();

                if (rs.next()) {

                    TxtUsername.setBackground(Color.red);
                    JOptionPane.showMessageDialog(null, "nombre de usuario no disponible");
                    cn.close();

                } else {

                    Connection cn2 = Conexion.Conectar();
                    String ConsultaSQLparagrabar = "update usuarios set nombre_usuario=?, email=?, telefono=?, username=?, tipo_nivel=?, estatus=? where id_usuario = '" + ID + "'";
                    PreparedStatement psr2 = cn2.prepareStatement(ConsultaSQLparagrabar);

                    psr2.setString(1, Nombre);
                    psr2.setString(2, mail);
                    psr2.setString(3, Telefono);
                    psr2.setString(4, username);
                    psr2.setString(5, permisos_String);
                    psr2.setString(6, estatus_String);
                    System.out.println(estatus_String);
                    System.out.println(ID);

                    psr2.executeUpdate();
                    cn2.close();
                    JOptionPane.showMessageDialog(null, "usuario actualizado exitosamente");

                }

            } catch (SQLException e) {
                System.err.print("error al actualizar " + e);
            }

        } else {
            JOptionPane.showMessageDialog(null, "debeles llenar todos los campos ");
        }


    }//GEN-LAST:event_jButton1_ActualizarActionPerformed

    private void jButton1_RestauraPASSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_RestauraPASSActionPerformed
        // TODO add your handling code here:
        
        RestaurarPassword restaura = new RestaurarPassword();
        restaura.setVisible(true);
    }//GEN-LAST:event_jButton1_RestauraPASSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacionUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CCMB_Estatus;
    private javax.swing.JComboBox<String> CMB_niveles;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtRegistradopor;
    private javax.swing.JTextField TxtTelefono;
    private javax.swing.JTextField TxtUsername;
    private javax.swing.JTextField Txt_mail;
    private javax.swing.JButton jButton1_Actualizar;
    private javax.swing.JButton jButton1_RestauraPASS;
    private javax.swing.JLabel jLabel1_Walpaper;
    private javax.swing.JLabel jLabel2_Nombre;
    private javax.swing.JLabel jLabel2_Nombre1;
    private javax.swing.JLabel jLabel2_Nombre2;
    private javax.swing.JLabel jLabel2_Nombre3;
    private javax.swing.JLabel jLabel2_Nombre4;
    private javax.swing.JLabel jLabel2_Nombre5;
    private javax.swing.JLabel jLabel2_Nombre6;
    private javax.swing.JLabel jLabel2_footer;
    private javax.swing.JLabel jLabel_titulo;
    // End of variables declaration//GEN-END:variables
}
