/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;

import java.sql.*;
import clases.Conexion;
import javax.swing.JOptionPane;

/**
 *
 * @author Victor
 */
public class Login extends javax.swing.JFrame {

    // enviar datos entre interfases 
    public static String user = "";
    public static String pass = "";

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setSize(400, 550);
        setResizable(false);
        setTitle("Acceso al sistema");
        setLocationRelativeTo(null);
        /// agregar la imaen 
        //// esto es opcional obedece al diseño del aplicativo 
        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel1_wallpaper.getWidth(), jLabel1_wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel1_wallpaper.setIcon(icono);
        this.repaint();

        // logo empresa 
        ImageIcon wallpaper_logo = new ImageIcon("src/images/DS.png");
        Icon icono_logo = new ImageIcon(wallpaper_logo.getImage().getScaledInstance(jLabel_Logo.getWidth(), jLabel_Logo.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Logo.setIcon(icono_logo);
        this.repaint();

    }

    /// metodo para cambiar el icono por defecto
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Logo = new javax.swing.JLabel();
        jButton1_acceder = new javax.swing.JButton();
        jLabel1_footer = new javax.swing.JLabel();
        Txt_user = new javax.swing.JTextField();
        Txt_password = new javax.swing.JPasswordField();
        jLabel1_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 28, 307, 220));

        jButton1_acceder.setBackground(new java.awt.Color(153, 153, 255));
        jButton1_acceder.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jButton1_acceder.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_acceder.setText("Acceder");
        jButton1_acceder.setBorder(null);
        jButton1_acceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_accederActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_acceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 458, 85, -1));

        jLabel1_footer.setText("Creado por Victor Carreño");
        getContentPane().add(jLabel1_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 497, -1, -1));

        Txt_user.setBackground(new java.awt.Color(153, 153, 255));
        Txt_user.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Txt_user.setForeground(new java.awt.Color(255, 255, 255));
        Txt_user.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Txt_user.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 352, 199, -1));

        Txt_password.setBackground(new java.awt.Color(153, 153, 255));
        Txt_password.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Txt_password.setForeground(new java.awt.Color(255, 255, 255));
        Txt_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Txt_password.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 412, 199, -1));
        getContentPane().add(jLabel1_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 400, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_accederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_accederActionPerformed
        // TODO add your handling code here:

        user = Txt_user.getText().trim();
        pass = Txt_password.getText().trim();

        if (!user.equals("") || !pass.equals("")) {
            try {
                Connection cn = Conexion.Conectar();
                PreparedStatement pst = cn.prepareStatement(
                        "select tipo_nivel, estatus from usuarios where username ='" + user
                        + "' and password = '" + pass + "'");

                ResultSet rs = pst.executeQuery();

                if (rs.next()) {
                    String tipoNivel = rs.getString("tipo_nivel");
                    String estatus = rs.getString("estatus");

                    if (tipoNivel.equalsIgnoreCase("Administrador") && estatus.equalsIgnoreCase("Activo")) {
                        dispose();
                        new Administrador().setVisible(true);

                    } else if (tipoNivel.equalsIgnoreCase("Capturista") && estatus.equalsIgnoreCase("Activo")) {
                        dispose();
                        new Capturista().setVisible(true);

                    } else if (tipoNivel.equalsIgnoreCase("Tecnico") && estatus.equalsIgnoreCase("Activo")) {
                        dispose();
                        new Tecnico().setVisible(true);

                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Datos de acceso incorrectos");
                    Txt_user.setText("");
                    Txt_password.setText("");
                }

            } catch (SQLException e) {
                System.err.println("error en el boton aceder " + e);
                JOptionPane.showMessageDialog(null, "!!error al inciar , contacte al administrador ");
            }

        } else {
            JOptionPane.showMessageDialog(null, "no se permite usuario o pas en blanco");
        }


    }//GEN-LAST:event_jButton1_accederActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Txt_password;
    private javax.swing.JTextField Txt_user;
    private javax.swing.JButton jButton1_acceder;
    private javax.swing.JLabel jLabel1_footer;
    private javax.swing.JLabel jLabel1_wallpaper;
    private javax.swing.JLabel jLabel_Logo;
    // End of variables declaration//GEN-END:variables
}
