/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Victor
 */
public class RegistrarUusuario extends javax.swing.JFrame {

    String user = "";

    /**
     * Creates new form RegistrarUusuario
     */
    public RegistrarUusuario() {
        initComponents();
        this.setLocationRelativeTo(null);
        user = Login.user;

        setTitle("Registro de nuevo usuario - Sesion  de " + user);
        setSize(630, 350);
        setResizable(false);

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        // metodo para cambiar el fono de pantalla de la interfas 
        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Walpaper.getWidth(), jLabel_Walpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Walpaper.setIcon(icono);
        this.repaint();

    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Txt_Mail = new javax.swing.JTextField();
        Txt_Nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Txt_Password = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Txt_Telefono = new javax.swing.JTextField();
        Txt_Username = new javax.swing.JTextField();
        CBM_Niveles = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        Jlabel_footer = new javax.swing.JLabel();
        jLabel_Walpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro de usuarios  ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        Txt_Mail.setBackground(new java.awt.Color(153, 153, 255));
        Txt_Mail.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        Txt_Mail.setForeground(new java.awt.Color(255, 255, 255));
        Txt_Mail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Txt_Mail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Txt_Mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 210, -1));

        Txt_Nombre.setBackground(new java.awt.Color(153, 153, 255));
        Txt_Nombre.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        Txt_Nombre.setForeground(new java.awt.Color(255, 255, 255));
        Txt_Nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Txt_Nombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Txt_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 210, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Telefono :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        Txt_Password.setBackground(new java.awt.Color(153, 153, 255));
        Txt_Password.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        Txt_Password.setForeground(new java.awt.Color(255, 255, 255));
        Txt_Password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Txt_Password.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Txt_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 210, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Permiso de :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre Usuario");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nombre");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PASS");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        Txt_Telefono.setBackground(new java.awt.Color(153, 153, 255));
        Txt_Telefono.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        Txt_Telefono.setForeground(new java.awt.Color(255, 255, 255));
        Txt_Telefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Txt_Telefono.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Txt_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 210, -1));

        Txt_Username.setBackground(new java.awt.Color(153, 153, 255));
        Txt_Username.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        Txt_Username.setForeground(new java.awt.Color(255, 255, 255));
        Txt_Username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Txt_Username.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Txt_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 210, -1));

        CBM_Niveles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Capturista", "Tecnico" }));
        getContentPane().add(CBM_Niveles, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 120, 100));

        Jlabel_footer.setText("Creado por Victor Carreño");
        getContentPane().add(Jlabel_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, -1));

        jLabel_Walpaper.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel_Walpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 3, 630, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        int permisos_cmb = 0;
        int validacion = 0;
        String nombre = "";
        String mail = "";
        String telefono = "";
        String username = "";
        String pass = "";

        String permisos_string = ""; // permiso String es para el combo box 

        mail = Txt_Mail.getText().trim();
        nombre = Txt_Nombre.getText().trim();
        telefono = Txt_Telefono.getText().trim();
        username = Txt_Username.getText().trim();
        pass = Txt_Password.getText().trim();
        permisos_cmb = CBM_Niveles.getSelectedIndex() + 1;

        if (mail.equals("")) {
            Txt_Mail.setBackground(Color.red);
            validacion++;
        }
        if (nombre.equals("")) {
            Txt_Nombre.setBackground(Color.red);
            validacion++;
        }
        if (telefono.equals("")) {
            Txt_Telefono.setBackground(Color.red);
            validacion++;
        }
        if (username.equals("")) {
            Txt_Username.setBackground(Color.red);
            validacion++;
        }
        if (pass.equals("")) {
            Txt_Password.setBackground(Color.red);
            validacion++;
        }
        /// estructura condicional para ver el valor que genera el comboBox 

        if (permisos_cmb == 1) {
            permisos_string = "Administrador";
        } else if (permisos_cmb == 2) {
            permisos_string = "Capturista";

        } else if (permisos_cmb == 3) {
            permisos_string = "Tecnico";
        }

        /// validacion de usuarios existente en las base de datos 
        try {
            Connection cn = Conexion.Conectar();
            PreparedStatement psr = cn.prepareStatement(
                    "Select username from usuarios where username = '" + username + "'");
            ResultSet rs = psr.executeQuery();

            if (rs.next()) {
                Txt_Username.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "Nombre de usuario no disponible");
                cn.close();

            } else {
                cn.close();

                if (validacion == 0) {
                    try {

                        Connection cn2 = Conexion.Conectar();
                        String ConsultaSQL = "insert into usuarios values (?,?,?,?,?,?,?,?,?)";
                        PreparedStatement pst2 = cn2.prepareStatement(ConsultaSQL);
                        pst2.setInt(1, 0);
                        pst2.setString(2, nombre);
                        pst2.setString(3, mail);
                        pst2.setString(4, telefono);
                        pst2.setString(5, username);
                        pst2.setString(6, pass);
                        pst2.setString(7, permisos_string);
                        pst2.setString(8, "Activo");
                        pst2.setString(9, user);

                        pst2.executeUpdate();
                        cn2.close();

                        Limpiar();

                        Txt_Mail.setBackground(Color.GREEN);
                        Txt_Username.setBackground(Color.GREEN);
                        Txt_Password.setBackground(Color.GREEN);
                        Txt_Nombre.setBackground(Color.GREEN);
                        Txt_Telefono.setBackground(Color.GREEN);

                        JOptionPane.showMessageDialog(null, "el registro fue exitoso");
                        this.dispose();

                    } catch (SQLException e) {
                        System.err.println("error en la vista regostro " + e);
                        JOptionPane.showMessageDialog(null, "Ocurrio un error en le registro , contacte al administraor del sistema ");
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Debe llenar todos los campos ");
                }

            }
        } catch (SQLException e) {
            System.err.println("ocurrio un error en la consulta SQL " + e);
            JOptionPane.showMessageDialog(null, "error al validar el usuario consulte con el administrador");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarUusuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarUusuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarUusuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarUusuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarUusuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBM_Niveles;
    private javax.swing.JLabel Jlabel_footer;
    private javax.swing.JTextField Txt_Mail;
    private javax.swing.JTextField Txt_Nombre;
    private javax.swing.JPasswordField Txt_Password;
    private javax.swing.JTextField Txt_Telefono;
    private javax.swing.JTextField Txt_Username;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_Walpaper;
    // End of variables declaration//GEN-END:variables

    /// metodo que permite limpiar los campos   
    public void Limpiar() {
        Txt_Mail.setText("");
        Txt_Username.setText("");
        Txt_Password.setText("");
        Txt_Nombre.setText("");
        Txt_Telefono.setText("");
        CBM_Niveles.setSelectedIndex(0);
    }
}