/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.sql.*;
import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Calendar;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Victor
 */
public class Registrar_equipo extends javax.swing.JFrame {

    int IDcliente_update = 0;
    String user = "";
    String nom_cliente = "";

    /**
     * Creates new form Registrar_equipo
     */
    public Registrar_equipo() {
        initComponents();
        user = Login.user;
        IDcliente_update = GestionarClientes.IDclienteUpdate;
        setTitle("Registrar un nuevo equipo para  " + nom_cliente);
        setSize(630, 445);
        setLocationRelativeTo(null);
        /// esto impide que el programa se cierre cuando finaliza esta interfas
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        try {
            Connection cn = Conexion.Conectar();
            String ElisaSQL = "select nombre_cliente from clientes where id_cliente = '" + IDcliente_update + "'";

            PreparedStatement pst = cn.prepareStatement(ElisaSQL);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                nom_cliente = rs.getString("nombre_cliente");

            } else {
            }

        } catch (SQLException e) {
            System.err.println("error al consultar cliente " + e);
        }

        // metodo que cambia el fondo de pantalla de la aplicacion 
        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel1_walpaper.getWidth(), jLabel1_walpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel1_walpaper.setIcon(icono);
        this.repaint();

        TxtnombreCliente.setText(nom_cliente);

    }
/// metodo para cambiar el icono de la interfas 
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane_observaciones = new javax.swing.JTextPane();
        jLabel_titulo = new javax.swing.JLabel();
        jLabel2_Nombre = new javax.swing.JLabel();
        jLabel2_Nombre1 = new javax.swing.JLabel();
        jLabel2_Nombre2 = new javax.swing.JLabel();
        jLabel2_Nombre3 = new javax.swing.JLabel();
        jLabel2_Nombre4 = new javax.swing.JLabel();
        jLabel2_Nombre5 = new javax.swing.JLabel();
        TxtnombreCliente = new javax.swing.JTextField();
        txtmodelo = new javax.swing.JTextField();
        TxtSerie = new javax.swing.JTextField();
        cmb_tipo_equipo = new javax.swing.JComboBox<>();
        cmb_marcas = new javax.swing.JComboBox<>();
        jButton_registrar = new javax.swing.JButton();
        jLabel1_walpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(jTextPane_observaciones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 330, 230));

        jLabel_titulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_titulo.setText("Registro de equipos");
        getContentPane().add(jLabel_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jLabel2_Nombre.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2_Nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2_Nombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2_Nombre.setText("nombre del cliente");
        getContentPane().add(jLabel2_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel2_Nombre1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2_Nombre1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2_Nombre1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2_Nombre1.setText("Tipo de equipo ");
        getContentPane().add(jLabel2_Nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel2_Nombre2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2_Nombre2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2_Nombre2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2_Nombre2.setText("Marca");
        getContentPane().add(jLabel2_Nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel2_Nombre3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2_Nombre3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2_Nombre3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2_Nombre3.setText("Modelo");
        getContentPane().add(jLabel2_Nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel2_Nombre4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2_Nombre4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2_Nombre4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2_Nombre4.setText("N serie");
        getContentPane().add(jLabel2_Nombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jLabel2_Nombre5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2_Nombre5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2_Nombre5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2_Nombre5.setText("Daño reportado");
        getContentPane().add(jLabel2_Nombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        TxtnombreCliente.setBackground(new java.awt.Color(153, 153, 255));
        TxtnombreCliente.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        TxtnombreCliente.setForeground(new java.awt.Color(255, 255, 255));
        TxtnombreCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtnombreCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(TxtnombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 210, 20));

        txtmodelo.setBackground(new java.awt.Color(153, 153, 255));
        txtmodelo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txtmodelo.setForeground(new java.awt.Color(255, 255, 255));
        txtmodelo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtmodelo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtmodelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 210, 20));

        TxtSerie.setBackground(new java.awt.Color(153, 153, 255));
        TxtSerie.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        TxtSerie.setForeground(new java.awt.Color(255, 255, 255));
        TxtSerie.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtSerie.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(TxtSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 210, 20));

        cmb_tipo_equipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laptop", "Desktop", "Multifuncional", "Impresora" }));
        getContentPane().add(cmb_tipo_equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        cmb_marcas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acer", "Apple", "HP", "Compaq", "Asus", "Dell", "Lenovo", "Sony", "Generico(clon)", "Samsung", "Pacard bell", "Olidata", "Gear", "E machine", "Toshiba", "No especificado" }));
        getContentPane().add(cmb_marcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jButton_registrar.setBackground(new java.awt.Color(153, 153, 225));
        jButton_registrar.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jButton_registrar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_registrar.setText("Registrar Equipo");
        jButton_registrar.setBorder(null);
        jButton_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_registrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 210, 35));
        getContentPane().add(jLabel1_walpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 445));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_registrarActionPerformed
        // TODO add your handling code here:
        int validacion = 0;
        String tipo_equipo, marca, modelo, num_serie, dia_ingreso, mes_ingreso, ano_ingreso, estatus, observaciones;
        
        
        tipo_equipo = cmb_tipo_equipo.getSelectedItem().toString();
        marca = cmb_marcas.getSelectedItem().toString(); /// investigar esto  
        modelo = txtmodelo.getText().trim();
        num_serie = TxtSerie.getText().trim();
        observaciones = jTextPane_observaciones.getText();
        estatus = "Nuevo Ingreso";
        
        //// registro de fechas
        
        Calendar calendar = Calendar.getInstance();
        
        dia_ingreso = Integer.toString(calendar.get(calendar.DATE));
        mes_ingreso = Integer.toString(calendar.get(calendar.MONTH));
        ano_ingreso = Integer.toString(calendar.get(calendar.YEAR));
        
        if (modelo.equals("")){
            txtmodelo.setBackground(Color.red);
            validacion ++; 
        }
        if (num_serie.equals("")){
            TxtSerie.setBackground(Color.red);
            validacion ++;
  
        }
         if (observaciones.equals("")){
             
             // camr por regla de negocio de Asomado Soft 
            jTextPane_observaciones.setText("Sin Observaciones ");
            
        }
         if (validacion == 0 ) {
             
             try {
                 Connection cn = Conexion.Conectar();
                 String alpeo = "insert into equipos values (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                 PreparedStatement pst = cn.prepareStatement(alpeo);
                 
                 pst.setInt(1, 0);
                 pst.setInt(2, IDcliente_update);
                 pst.setString(3, tipo_equipo);
                 pst.setString(4, marca);
                 pst.setString(5, modelo);
                 pst.setString(6, num_serie);
                 pst.setString(7, dia_ingreso);
                 pst.setString(8, mes_ingreso);
                 pst.setString(9, ano_ingreso);
                 pst.setString(10, observaciones);
                 pst.setString(11, estatus);
                 pst.setString(12, user);
                 pst.setString(13, "");
                 pst.setString(14, "");
                 
                 pst.executeUpdate();
                 cn.close();
                 
                 TxtnombreCliente.setBackground(Color.yellow);
                 txtmodelo.setBackground(Color.yellow);
                 TxtSerie.setBackground(Color.yellow);
                 
                    JOptionPane.showMessageDialog(null, "Registro Exitoso");
                    this.dispose();
                 
             } catch (SQLException e) {
                 System.err.println("error en registrar equipo " +e);
                 JOptionPane.showMessageDialog(null, "contacte al administradoe hay un error ");
             }
            
        } else {
             JOptionPane.showMessageDialog(null, "debe de llenar todos los campos ");
        }
        
        
        

    }//GEN-LAST:event_jButton_registrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar_equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar_equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar_equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar_equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrar_equipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtSerie;
    private javax.swing.JTextField TxtnombreCliente;
    private javax.swing.JComboBox<String> cmb_marcas;
    private javax.swing.JComboBox<String> cmb_tipo_equipo;
    private javax.swing.JButton jButton_registrar;
    private javax.swing.JLabel jLabel1_walpaper;
    private javax.swing.JLabel jLabel2_Nombre;
    private javax.swing.JLabel jLabel2_Nombre1;
    private javax.swing.JLabel jLabel2_Nombre2;
    private javax.swing.JLabel jLabel2_Nombre3;
    private javax.swing.JLabel jLabel2_Nombre4;
    private javax.swing.JLabel jLabel2_Nombre5;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane_observaciones;
    private javax.swing.JTextField txtmodelo;
    // End of variables declaration//GEN-END:variables
}
