/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;
import java.sql.*;
import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;


/**
 *
 * @author Victor
 */
public class RestaurarPassword extends javax.swing.JFrame {
    String user = "";
    String user_update = "";
    

    /**
     * Creates new form RestaurarPassword
     */
    public RestaurarPassword() {
        initComponents();
        user = Login.user;
        user_update = GestionarUsuarios.user_update;
        
        setSize(360, 260);
        setResizable(false);
        setTitle("Cambio de password para " + user_update);
        setLocationRelativeTo(null);
        
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel1_Wallpaper.getWidth(), jLabel1_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel1_Wallpaper.setIcon(icono);
        this.repaint();
        
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Txt_Password = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Txt_Password_confirmacion = new javax.swing.JPasswordField();
        jButton1_RestauraPASS = new javax.swing.JButton();
        jLabel1_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cambio de Pasword ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        Txt_Password.setBackground(new java.awt.Color(153, 153, 255));
        Txt_Password.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        Txt_Password.setForeground(new java.awt.Color(255, 255, 255));
        Txt_Password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Txt_Password.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Txt_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 210, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("nuevo PASS");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(" confirmar pass");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        Txt_Password_confirmacion.setBackground(new java.awt.Color(153, 153, 255));
        Txt_Password_confirmacion.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        Txt_Password_confirmacion.setForeground(new java.awt.Color(255, 255, 255));
        Txt_Password_confirmacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Txt_Password_confirmacion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Txt_Password_confirmacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 210, -1));

        jButton1_RestauraPASS.setBackground(new java.awt.Color(153, 153, 225));
        jButton1_RestauraPASS.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jButton1_RestauraPASS.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_RestauraPASS.setText("Restaura password");
        jButton1_RestauraPASS.setBorder(null);
        jButton1_RestauraPASS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_RestauraPASSActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_RestauraPASS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 210, 35));
        getContentPane().add(jLabel1_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_RestauraPASSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_RestauraPASSActionPerformed
        // TODO add your handling code here:
        
        String password;
        String confirmacion_password;
        
        password = Txt_Password.getText().trim();
        confirmacion_password = Txt_Password_confirmacion.getText().trim();
        
        if (!password.equals("")&& !confirmacion_password.equals("")) {
            if (password.equals(confirmacion_password)) {
                
                try {
                    Connection cn = Conexion.Conectar();
                    String ConsultaSQL = "update usuarios set password=? where username= '" +user_update + "'";
                    PreparedStatement pst =  cn.prepareStatement(ConsultaSQL);
                    
                    pst.setString(1, password);
                    
                    pst.executeUpdate();
                    cn.close();
                    
                    Txt_Password.setBackground(Color.green);
                    Txt_Password_confirmacion.setBackground(Color.green);
                    JOptionPane.showMessageDialog(null, "la contraseña se restauro correctamente "
                            + " correctamente");
                    
                    this.dispose();
                    
                    
                } catch (SQLException e) {
                    System.err.println("error en la actualizacion " +e );
                    JOptionPane.showMessageDialog(null, "error en la actualizacion de pasword  , contacte al administrador");
                }
                
            } else {
                Txt_Password_confirmacion.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "las contraseñas no coinciden");
            }
            
        } else {
            Txt_Password.setBackground(Color.red);
            Txt_Password_confirmacion.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "no se admiten contraseñas vacias");
        }
    }//GEN-LAST:event_jButton1_RestauraPASSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestaurarPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestaurarPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestaurarPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestaurarPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestaurarPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Txt_Password;
    private javax.swing.JPasswordField Txt_Password_confirmacion;
    private javax.swing.JButton jButton1_RestauraPASS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_Wallpaper;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
