/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import clases.Conexion;
import java.sql.*;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.FileOutputStream;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;


/**
 *
 * @author Victor
 */
public class Tecnico extends javax.swing.JFrame {
    
    int sesion_usuario;
    String user;
    String nombre_usuario;

    /**
     * Creates new form Capturista
     */
    public Tecnico() {
        initComponents();
        user = Login.user;
        sesion_usuario = Administrador.sesion_usuario;
        
        
        setSize(550, 300);
        setResizable(false);
        
        setLocationRelativeTo(null);
        setTitle("Tecnico sesion de -" + user);
        //// este if determina si la sesion esta iniciada por un administrador  es decir que si la condicion de mas abajo no se cumple eso quere decir que corresponde a un capturista
        if (sesion_usuario == 1){
            setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        }else{
            setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        }
        // metodo que cambia el fondo de pantalla de la aplicacion 
        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel1_walpaper.getWidth(), jLabel1_walpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel1_walpaper.setIcon(icono);
        this.repaint();
        
        try {
            Connection cn = Conexion.Conectar();
            String ConsultaSql = "select nombre_usuario from usuarios where username ='"+ user + "'";
            PreparedStatement pst = cn.prepareStatement(ConsultaSql);
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                nombre_usuario = rs.getString("nombre_usuario");
                jLabel1_nombreUsuaurio.setText("bienvenido "+ nombre_usuario);
                
            }
        } catch (SQLException e) {
            System.err.println("error al obtener el usuario para el label nombre de usuario en la vista Tecnico " + e);
        }
        
    }
    
    //metodo para cambiar el icono de la interfas
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1_nombreUsuaurio = new javax.swing.JLabel();
        jButton1_GestionarEquipo = new javax.swing.JButton();
        jButton1_GraficaStatus = new javax.swing.JButton();
        jButton1_GraficaMarca = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Jlabel_footer = new javax.swing.JLabel();
        jLabel1_walpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1_nombreUsuaurio.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel1_nombreUsuaurio.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_nombreUsuaurio.setText("jLabel1");
        getContentPane().add(jLabel1_nombreUsuaurio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton1_GestionarEquipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/apoyo-tecnico.png"))); // NOI18N
        jButton1_GestionarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_GestionarEquipoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_GestionarEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 120, 100));

        jButton1_GraficaStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/grafica.png"))); // NOI18N
        jButton1_GraficaStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_GraficaStatusActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_GraficaStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 120, 100));

        jButton1_GraficaMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/grafica.png"))); // NOI18N
        jButton1_GraficaMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_GraficaMarcaActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_GraficaMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 120, 100));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gestion de equipo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Grafica de estatud");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Grafica de Marca");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, -1));

        Jlabel_footer.setText("Creado por Victor Carreño");
        getContentPane().add(Jlabel_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));
        getContentPane().add(jLabel1_walpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_GestionarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_GestionarEquipoActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jButton1_GestionarEquipoActionPerformed

    private void jButton1_GraficaStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_GraficaStatusActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jButton1_GraficaStatusActionPerformed

    private void jButton1_GraficaMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_GraficaMarcaActionPerformed
        // TODO add your handling code here:
        
            
           
            
         
                      
        
    }//GEN-LAST:event_jButton1_GraficaMarcaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tecnico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jlabel_footer;
    private javax.swing.JButton jButton1_GestionarEquipo;
    private javax.swing.JButton jButton1_GraficaMarca;
    private javax.swing.JButton jButton1_GraficaStatus;
    private javax.swing.JLabel jLabel1_nombreUsuaurio;
    private javax.swing.JLabel jLabel1_walpaper;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
